// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/getting-started":{"path":"getting-started","id":"docs/getting-started","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/alert/index":{"id":"components/alert/index","path":"components/alert","parentId":"DocLayout","meta":{"_atom_route":true}},"components/button/index":{"id":"components/button/index","path":"components/button","parentId":"DocLayout","meta":{"_atom_route":true}},"components/countDown/index":{"id":"components/countDown/index","path":"components/count-down","parentId":"DocLayout","meta":{"_atom_route":true}},"components/image/index":{"id":"components/image/index","path":"components/image","parentId":"DocLayout","meta":{"_atom_route":true}},"components/modal/index":{"id":"components/modal/index","path":"components/modal","parentId":"DocLayout","meta":{"_atom_route":true}},"components/upload/index":{"id":"components/upload/index","path":"components/upload","parentId":"DocLayout","meta":{"_atom_route":true}},"components/vitual-list/index":{"id":"components/vitual-list/index","path":"components/vitual-list","parentId":"DocLayout","meta":{"_atom_route":true}},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'docs/getting-started': React.lazy(() => import(/* webpackChunkName: "docs__getting-started.md" */'D:/MyReactComponents/docs/getting-started.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'D:/MyReactComponents/docs/index.md')),
'components/alert/index': React.lazy(() => import(/* webpackChunkName: "alert__index.md" */'D:/MyReactComponents/src/alert/index.md')),
'components/button/index': React.lazy(() => import(/* webpackChunkName: "button__index.md" */'D:/MyReactComponents/src/button/index.md')),
'components/countDown/index': React.lazy(() => import(/* webpackChunkName: "countDown__index.md" */'D:/MyReactComponents/src/countDown/index.md')),
'components/image/index': React.lazy(() => import(/* webpackChunkName: "image__index.md" */'D:/MyReactComponents/src/image/index.md')),
'components/modal/index': React.lazy(() => import(/* webpackChunkName: "modal__index.md" */'D:/MyReactComponents/src/modal/index.md')),
'components/upload/index': React.lazy(() => import(/* webpackChunkName: "upload__index.md" */'D:/MyReactComponents/src/upload/index.md')),
'components/vitual-list/index': React.lazy(() => import(/* webpackChunkName: "vitual-list__index.md" */'D:/MyReactComponents/src/vitual-list/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
